### ISSUE TITLE
Hactober

### ISSUE THREAD

**Issue by AmanBansal1998** [jaykay12/jaykay12.github.io#13]
I would like to know

**Comment by jaykay12** [comment]
Yes. Surely @AmanBansal1998 
Here's the site from where you can sign up for Hacktoberfest 2018:

>  [https://hacktoberfest.digitalocean.com/](url)

You need to open 5 Pull Requests on any Public Repository hosted on GitHub & you will grab free tshirt & stickers from GitHub & DigitalOcean.
