### ISSUE TITLE
Sending email in static webpages

### ISSUE THREAD

**Issue by meetanubhav** [jaykay12/jaykay12.github.io#15]
#4 
Yes it is possible using https;//freespree.io They provide with this feature of sending emails in static hosted web pages.

```
<!DOCTYPE html>
<html>
<head></head>
<body>
		<form action="https://formspree.io/your@email.com"
      method="POST">
    Message<input type="text" name="name">
    <br>
    To:<input type="email" name="_replyto">
    <input type="submit" value="Send">
</form>
</body>
</html> 
```
@jaykay12

**Comment by jaykay12** [comment]
Yes @meetanubhav I just configured my mailing system using formspree.io as suggested by you. Thanks again. Happy hacking :octocat:
