### ISSUE TITLE
Profile Pic can't be centered in enclosing div

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/jaykay12.github.io#22]
**Current Behavior:**
![screenshot from 2018-10-06 16-51-16](https://user-images.githubusercontent.com/13948542/46570882-197b1780-c989-11e8-8bad-f780de57d1c6.png)

**Required Behavior:**
Image need to be centered inside the div

**Required Information:**
The following lines in `index.html` needs to be modified

> `<div class="col-xs-12 col-md-6" style="text-align:center">`
> `<img src="img/about.jpg" class="img-responsive img-thumbnail" alt="" style="width:80%; margin: 0 auto">`
> `</div>`

**Comment by mbledkowski** [comment]
I can do this

**Comment by jaykay12** [comment]
Resolved by @mmacq with PR #23 :nerd_face:
