### ISSUE TITLE
Dribbble fa-icon need replacement by Quora fa-icon

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/jaykay12.github.io#3]

**Comment by daniloff200** [comment]
hey :) I've made a PR for that issue #9

**Comment by praveen-me** [comment]
I am going to work on the issue. Can I do this?

**Comment by jaykay12** [comment]
Hello @praveen-me ,the Issue has been resolved #9 by @daniloff200
Thanks for your initiative, I really appreciate your contributions. You can still solve other issues as of now.

Happy Hacking :octocat: :nerd_face:
