### ISSUE TITLE
Mail Server Need Reconfiguration

### ISSUE THREAD

**Issue by jaykay12** [jaykay12/jaykay12.github.io#4]
![screenshot from 2018-09-03 13-32-44](https://user-images.githubusercontent.com/13948542/44974679-020dd080-af7e-11e8-8e44-39d5804d91b4.png)

### Important
PHP Script for the mail server is written but since I am using GitHub Pages for hosting my portfolio site, so not able to run backend scripts. Is there any work arounds?

**Comment by garstikaitis** [comment]
You can use node-mailer to send emails. It will require you to run an instance somewhere. Good call would be to use Heroku. Let me know if you need help. I could help you to get it to work, but you will need to add your credentials of email client

**Comment by vchrombie** [comment]
You can use https://formspree.io, it is very easy and works on GitHub pages even. But the only drawback is your email id will be visible in the source code.

**Comment by meetanubhav** [comment]
#13 
#Hacktoberfest
@jaykay12  YES! It is totally possible. Using https://formspree.io . You just need to add your email address and the rest will be done. Just type you custom message and the receiver email address. HOLA!!!
<html>
<head></head>
<form action="https://formspree.io/your@email.com"
      method="POST">
    Message<input type="text" name="name">
    <br>
    To:<input type="email" name="_replyto">
 <br>
    <input type="submit" value="Send">
</form>
</body>
</html>

**Comment by jaykay12** [comment]
Yeahh Thanks a lot. It actually saved me alot. Actually I need it for my personal portfolio so, revealing email id in the source code is not a lot concern.
Thanks again @vchrombie & @meetanubhav  :octocat:

**Comment by meetanubhav** [comment]
Also you can write a script and authorise it. Wothout using Third party
application.

**Comment by meetanubhav** [comment]
@jaykay12 #15 #13 
Steps to configure without using 3rd party apps.

1. Open google drive and open excel sheet.
2. Next select script editor in the google sheet.
3. Write JavaScript file for your configuration.
4. Set the TO_ADDRESS in the Script ( in this column write your email address)
5. Save a New Version of Your Script
        Go to File-> Manager Version option to set Version
6. Publish the Updated Script as a Web App
7. Authorize the Script to Send Emails
    Click Continue to authorize this app:
    next,Copy the web app URL to your clipboard / Notepad. Then click “OK”.
8. Create Your Basic HTML Form
    In form action method = "adress this google drive link file"

DONE!!

**Comment by jaykay12** [comment]
Apparantly, Using 3rd party applications like [formspree.io](https://formspree.io/) doesn't look like a problem to me. I just configured it & it's working quite nicely.

Incase, in near future if the number of messages increase then I can switch to your latter solution or to the one as proposed by @garstikaitis

**Comment by meetanubhav** [comment]
But using sheets you can have all the messages in a single excel file. It
would be more convenient to you.
And also formspree has some restrictions like 50 messages free for a month.
